language: julia
julia:
  - 1.5.0
  - nightly
before_install:
  - sudo apt-get update -qq;
    eval "$(curl -Ss https://raw.githubusercontent.com/neovim/bot-ci/master/scripts/travis-setup.sh) nightly-x64";
script:
    - julia -e 'using Pkg; Pkg.init(); Pkg.instantiate(); Pkg.develop(PackageSpec(path=pwd())); Pkg.test("Neovim")'
